module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    VERIFY_OTP: "VERIFY_OTP",
    ADD_MEMBER: "ADD_MEMBER",
    ADD_ROLE: "ADD_ROLE",
    ADD_BRAND: "ADD_BRAND",
    ADD_BRAND_TYPE: "ADD_BRAND_TYPE",
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_CATEGORY: "ADD_PRODUCT_CATEGORY",
    ADD_PRODUCT_SIZE: "ADD_PRODUCT_SIZE",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },
  CONFIRMATION_MODAL_CLOSE_TYPES: {
    ROLE_DELETE: "ROLE_DELETE",
    BRAND_TYPE_DELETE: "BRAND_TYPE_DELETE",
    BRAND_DELETE: "BRAND_DELETE",
    PRODUCT_DELETE: "PRODUCT_DELETE",
    PRODUCT_CATEGORY_DELETE: "PRODUCT_CATEGORY_DELETE",
    PRODUCT_SIZE_DELETE: "PRODUCT_SIZE_DELETE",

  },
});
